DECLARE @VARVENC DATETIME, @VARATUAL DATETIME
SET @VARVENC = '2022-03-10'
SET @VARATUAL = '2022-04-30'

SELECT
CASE
WHEN @VARATUAL > @VARVENC
THEN 'PRODUTO VENC'
ELSE 'NA VALIDADE'
END
----
SELECT
CustomerKey,
FirstName,
Gender,
CASE WHEN
	GENDER = 'M' THEN 'MASCULINO'
	ELSE 'FEMININO'
END
FROM
DimCustomer