CREATE OR ALTER TRIGGER tgRecusarTabelas
ON DATABASE
FOR CREATE_TABLE,ALTER_TABLE,DROP_TABLE
AS
BEGIN
	PRINT 'NÃO É PERMITIDO A CRIAÇÃO'
	ROLLBACK
END

CREATE TABLE test(ID INT)
---
---
ENABLE TRIGGER tgRecusarTabelas ON DATABASE

DISABLE TRIGGER ALL ON DATABASE

DROP TRIGGER tgRecusarTabelas ON DATABASE
---
---
